In [5]:
import torch

## How Chain-rule works in MSE Loss 

In [6]:
model = torch.nn.Sequential(
     torch.nn.Linear(2,2,bias=False),
     torch.nn.Linear(2,2,bias=False),
     torch.nn.Linear(2,1,bias=False)
     )

criterion = torch.nn.MSELoss()
optim = torch.optim.SGD(model.parameters(), lr=.01)

inp = torch.tensor([[1.,2.]])

print(model[0].weight)
print(model[1].weight)
print(model[2].weight)

Parameter containing:
tensor([[ 0.0546, -0.1123],
        [ 0.4652,  0.0651]], requires_grad=True)
Parameter containing:
tensor([[-0.4510, -0.5393],
        [-0.0835,  0.1739]], requires_grad=True)
Parameter containing:
tensor([[-0.4123, -0.4128]], requires_grad=True)


In [7]:
y_pred = model.forward(inp)
y = torch.tensor([[3.0]])
loss = criterion.forward(y_pred, y)
loss

tensor(8.6899, grad_fn=<MseLossBackward0>)

In [8]:
loss.backward()

In [9]:
print(model[0].weight.grad)
print(model[1].weight.grad)
print(model[2].weight.grad)

tensor([[-1.2997, -2.5993],
        [-0.8875, -1.7750]])
tensor([[-0.4134,  1.4471],
        [-0.4139,  1.4491]])
tensor([[ 1.4408, -0.6943]])


In [10]:
res = model[1].forward(model[0].forward(inp))
res

tensor([[-0.2444,  0.1178]], grad_fn=<MmBackward0>)

$w_1^ \prime = a^2w_1 + abw_2 - ya$ 

In [11]:
((res[0,0]**2)*model[2].weight[0,0] + res[0,0]*res[0,1]*model[2].weight[0,1] - res[0,0]*y[0,0])*2

tensor(1.4408, grad_fn=<MulBackward0>)

In [12]:
((res[0,1]**2)*model[2].weight[0,1] + res[0,0]*res[0,1]*model[2].weight[0,0] - res[0,1]*y[0,0])*2

tensor(-0.6943, grad_fn=<MulBackward0>)

## How Chain-rule works in NLLoss

In [13]:
model = torch.nn.Sequential(
     torch.nn.Linear(2,2,bias=False),
     torch.nn.Linear(2,2,bias=False)
     )

criterion = torch.nn.NLLLoss()
optim = torch.optim.SGD(model.parameters(), lr=.01)

inp = torch.tensor([[1.,2.]])

print(model[0].weight)
print(model[1].weight)

Parameter containing:
tensor([[ 0.6755, -0.2917],
        [-0.1681, -0.5040]], requires_grad=True)
Parameter containing:
tensor([[-0.6580, -0.1301],
        [-0.6238, -0.6303]], requires_grad=True)


In [14]:
y = torch.tensor([0])

y_pred = model.forward(inp)
print(y_pred)

loss = criterion.forward(y_pred, y)
print(loss)

tensor([[0.0924, 0.6838]], grad_fn=<MmBackward0>)
tensor(-0.0924, grad_fn=<NllLossBackward0>)


In [15]:
loss.backward()
print(model[0].weight.grad)
print(model[1].weight.grad)

tensor([[0.6580, 1.3160],
        [0.1301, 0.2602]])
tensor([[-0.0922,  1.1761],
        [ 0.0000, -0.0000]])


In [16]:
res0 = model[0].forward(inp)
res1 = model[1].forward(res0)
print(res0)
print(res1)

tensor([[ 0.0922, -1.1761]], grad_fn=<MmBackward0>)
tensor([[0.0924, 0.6838]], grad_fn=<MmBackward0>)


In [17]:
res0[0,0]

tensor(0.0922, grad_fn=<SelectBackward0>)