In [107]:
import torch
import torch.nn as nn

In [136]:
a = torch.tensor([[1.,2.]])
l1 = nn.Linear(2,3,bias=False)

In [141]:
criterion = nn.CrossEntropyLoss()
l1.zero_grad()

output = l1.forward(a)
output

tensor([[-0.9932,  0.9256, -0.2804]], grad_fn=<MmBackward0>)

In [142]:
loss = criterion.forward(output, torch.tensor([1]))

print(l1.weight)
print(loss)

Parameter containing:
tensor([[ 0.1413, -0.5672],
        [ 0.2291,  0.3482],
        [ 0.0463, -0.1633]], requires_grad=True)
tensor(0.3689, grad_fn=<NllLossBackward0>)


In [143]:
l1.zero_grad()
loss.backward()
print(l1.weight.grad)

tensor([[ 0.1015,  0.2030],
        [-0.3085, -0.6171],
        [ 0.2070,  0.4141]])


In [144]:
output.softmax(dim=1)

tensor([[0.1015, 0.6915, 0.2070]], grad_fn=<SoftmaxBackward0>)

In [145]:
loss.grad_fn.next_functions[0]

(<LogSoftmaxBackward0 at 0x7ff63c905c10>, 0)

${p_a}=\frac{e^a}{e^a + e^b +e^c} \implies \frac{d_{p_a}}{da}=\frac{e^a-e^a*e^a}{(e^a + e^b +e^c)^2} = p_a(1-p_a)$

${p_a}=\frac{e^a}{e^a + e^b +e^c} \implies \frac{d_{p_a}}{db}=\frac{0-e^b*e^a}{(e^a + e^b +e^c)^2} = -p_b*p_a$

${p_a}=\frac{e^a}{e^a + e^b +e^c} \implies \frac{d_{p_a}}{dc}=\frac{0-e^c*e^a}{(e^a + e^b +e^c)^2} = -p_c*p_a$


$CrossEntropy= -log(p) \implies d_{cr}= -d(log)*d(softmax) = -\frac{1}{p}*d(softmax) \implies $  

$-\frac{1}{p_a} * p_a(1-p_a) = p_a -1$

$-\frac{1}{p_a} * -p_b*p_a = p_b$

$-\frac{1}{p_a} * -p_a*p_b = p_c$

