In [9]:
import torch

In [10]:
model = torch.nn.Sequential(
     torch.nn.Linear(2,2,bias=False),
     torch.nn.Linear(2,2,bias=False),
     torch.nn.Linear(2,1,bias=False)
     )

criterion = torch.nn.MSELoss()
optim = torch.optim.SGD(model.parameters(), lr=.01)

inp = torch.tensor([[1.,2.]])

print(model[0].weight)
print(model[1].weight)
print(model[2].weight)

Parameter containing:
tensor([[-0.5164,  0.1844],
        [-0.0997,  0.1351]], requires_grad=True)
Parameter containing:
tensor([[0.2676, 0.5283],
        [0.0850, 0.0018]], requires_grad=True)
Parameter containing:
tensor([[ 0.2139, -0.0796]], requires_grad=True)


In [11]:
y_pred = model.forward(inp)
y = torch.tensor([[3.0]])
loss = criterion.forward(y_pred, y)
loss

tensor(8.9294, grad_fn=<MseLossBackward0>)

In [12]:
loss.backward()

In [13]:
print(model[0].weight.grad)
print(model[1].weight.grad)
print(model[2].weight.grad)

tensor([[-0.3016, -0.6032],
        [-0.6744, -1.3489]])
tensor([[ 0.1887, -0.2178],
        [-0.0702,  0.0811]])
tensor([[-0.3020,  0.0731]])


In [14]:
res = model[1].forward(model[0].forward(inp))
res

tensor([[ 0.0505, -0.0122]], grad_fn=<MmBackward0>)

$w_1^ \prime = a^2w_1 + abw_2 - ya$ 

In [15]:
((res[0,0]**2)*model[2].weight[0,0] + res[0,0]*res[0,1]*model[2].weight[0,1] - res[0,0]*y[0,0])*2

tensor(-0.3020, grad_fn=<MulBackward0>)

In [16]:
((res[0,1]**2)*model[2].weight[0,1] + res[0,0]*res[0,1]*model[2].weight[0,0] - res[0,1]*y[0,0])*2

tensor(0.0731, grad_fn=<MulBackward0>)