<a href="https://colab.research.google.com/github/M-Amrollahi/Personal-Notes/blob/master/ML-notes/how_normalizationd_work.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [55]:
import scipy
import numpy as np
import sklearn.preprocessing as prec

In [58]:
np.random.seed(50)
a = np.random.randint(0,10,(6,3))
a

array([[0, 0, 1],
       [4, 6, 5],
       [6, 6, 5],
       [2, 7, 4],
       [3, 6, 4],
       [1, 5, 9]])

# Normalize data on MAX
 on instance

In [81]:
p = prec.normalize(a,norm="max")

t = a/a.max(axis=1)[:,np.newaxis]

np.allclose(p,t)

True

# Normalize data on L1
L1 = sum(x1,x2,...)

on instance

In [82]:
p = prec.normalize(a,norm="l1")

t = a/a.sum(axis=1)[:,np.newaxis]
np.allclose(p,t)

True

# Normalize data on L2
L2 = sqrt(sum(x1**2,x2**2...))

on instance

In [83]:
p = prec.normalize(a,norm="l2")
t = a/np.power(np.power(a,2).sum(axis=1),.5)[:,np.newaxis]

np.allclose(p,t)

True

# Normalize data

on each feature

In [102]:
p = prec.scale(a)

mean = a.mean(axis=0)
std = a.std(axis=0)
t = (a-mean)/std

np.allclose(p,t)

True

In [51]:
prec.binarize(a,threshold= 5)

array([[0, 1, 1, 0, 1],
       [0, 0, 0, 1, 0],
       [0, 1, 1, 0, 0],
       [0, 1, 0, 0, 1],
       [1, 1, 1, 1, 0],
       [1, 1, 0, 0, 1],
       [1, 0, 1, 0, 0],
       [0, 0, 1, 1, 0],
       [0, 0, 1, 0, 0],
       [0, 1, 0, 0, 0]])

# Starndard Normalization 

(x-mean)/std

on each feature


In [107]:
mean = a.mean(axis=0)
std = a.std(axis=0)


smodel = prec.StandardScaler()
smodel.fit(a)
p = smodel.transform(a)
t = (a-mean)/std

np.allclose(p,t)

True

# MiaMax normalization

(a-min)/(max-min)

on each feature

In [110]:
model = prec.MinMaxScaler()
p = model.fit_transform(a)

t = (a - a.min(axis=0)) / (a.max(axis=0) - a.min(axis=0))

np.allclose(p,t)

True

In [111]:
prec.minmax_scale(a)

array([[0.        , 0.        , 0.        ],
       [0.66666667, 0.85714286, 0.5       ],
       [1.        , 0.85714286, 0.5       ],
       [0.33333333, 1.        , 0.375     ],
       [0.5       , 0.85714286, 0.375     ],
       [0.16666667, 0.71428571, 1.        ]])

In [122]:
a=prec.OneHotEncoder()
a.fit([[1],[3]])

OneHotEncoder()

In [124]:
a.transform([[3]])

<1x2 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in Compressed Sparse Row format>

In [135]:
b=a.transform([[1]])

In [138]:
b.toarray()

array([[1., 0.]])