<a href="https://colab.research.google.com/github/M-Amrollahi/Personal-Notes/blob/master/ML-notes/pytorch-cheet-sheet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

## Number of elements  in tensor

In [2]:
a = torch.arange(22)
a.nelement()

22

## Flatten the tensor, starts from each dim

In [ ]:
torch.flatten(torch.rand((3,3,3)) , start_dim=1)

tensor([[0.1783, 0.8209, 0.0261, 0.3833, 0.7992, 0.1784, 0.8311, 0.6818, 0.6363],
        [0.1738, 0.1535, 0.6898, 0.9236, 0.3581, 0.2190, 0.3062, 0.9067, 0.4804],
        [0.4577, 0.4426, 0.5322, 0.4159, 0.2990, 0.6162, 0.7050, 0.1627, 0.4601]])

## Chunk by number

In [ ]:
a = torch.arange(22)
a.chunk(3)

(tensor([0, 1, 2, 3, 4, 5, 6, 7]),
 tensor([ 8,  9, 10, 11, 12, 13, 14, 15]),
 tensor([16, 17, 18, 19, 20, 21]))

## Change the order of dims

In [ ]:
print(a.view(11,2))
torch.permute( a.view(11,2), dims=(1,0))

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21]])


tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21]])

In [ ]:
z = torch.Generator().manual_seed(12)
torch.randperm(4, generator= z)

tensor([3, 2, 1, 0])

## if the type of the tensor is any kinds of float.

In [ ]:
a.is_floating_point()

False

## Convert object to tesor

In [ ]:
torch.asarray((1,2,3,4.0))

# keep grads
torch.as_tensor([1,2,3])

tensor([1, 2, 3])

## Convert from np

In [ ]:
torch.from_numpy(np.arange(10))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## indeces of each non-zero element

In [ ]:
print(a.view(-1,2))
a.view(-1,2).argwhere()

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21]])


tensor([[ 0,  1],
        [ 1,  0],
        [ 1,  1],
        [ 2,  0],
        [ 2,  1],
        [ 3,  0],
        [ 3,  1],
        [ 4,  0],
        [ 4,  1],
        [ 5,  0],
        [ 5,  1],
        [ 6,  0],
        [ 6,  1],
        [ 7,  0],
        [ 7,  1],
        [ 8,  0],
        [ 8,  1],
        [ 9,  0],
        [ 9,  1],
        [10,  0],
        [10,  1]])

## Split the tensor like in batch processing

In [ ]:
a.split(3)

(tensor([0, 1, 2]),
 tensor([3, 4, 5]),
 tensor([6, 7, 8]),
 tensor([ 9, 10, 11]),
 tensor([12, 13, 14]),
 tensor([15, 16, 17]),
 tensor([18, 19, 20]),
 tensor([21]))

In [ ]:
a = torch.arange(10).reshape(5,2)
a
torch.split(a, 1)
torch.split(a, [1,4])

(tensor([[0, 1]]),
 tensor([[2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]))

## Horizontally split the tensor

In [ ]:
t = torch.arange(16.0).reshape(4,4)
t
torch.hsplit(t, 2)
#torch.hsplit(t, [3, 6])

(tensor([[ 0.,  1.],
         [ 4.,  5.],
         [ 8.,  9.],
         [12., 13.]]),
 tensor([[ 2.,  3.],
         [ 6.,  7.],
         [10., 11.],
         [14., 15.]]))

## Split the tesnor in depth

In [ ]:
t = torch.arange(16.0).reshape(2, 2, 4)
t
torch.dsplit(t, 2)

(tensor([[[ 0.,  1.],
          [ 4.,  5.]],
 
         [[ 8.,  9.],
          [12., 13.]]]),
 tensor([[[ 2.,  3.],
          [ 6.,  7.]],
 
         [[10., 11.],
          [14., 15.]]]))

## Select the index by dim

In [ ]:
x = torch.randn(3, 4)
print(x)
indices = torch.tensor([0, 2])
#torch.index_select(x, 0, indices)
torch.index_select(x, 1, indices)

tensor([[-1.9647, -0.2388,  0.4811,  0.2231],
        [-1.1043, -0.4001, -1.9548, -0.8543],
        [-0.9942,  1.1137, -0.1217, -0.7968]])


tensor([[-1.9647,  0.4811],
        [-1.1043, -1.9548],
        [-0.9942, -0.1217]])

## select by mask

In [ ]:
x = torch.randn(3, 4)
print(x)
mask = x.ge(0.5)
print(mask)
torch.masked_select(x, mask)

tensor([[ 1.6199,  1.1587,  0.4375,  0.1795],
        [ 2.0399,  1.6997, -0.2237, -0.5441],
        [-0.8154,  1.0232, -1.1076, -0.0195]])
tensor([[ True,  True, False, False],
        [ True,  True, False, False],
        [False,  True, False, False]])


tensor([1.6199, 1.1587, 2.0399, 1.6997, 1.0232])

## return the elemnts by the index view as 1-D

In [ ]:
src = torch.tensor([[4, 3, 5],
                    [6, 7, 8]])
torch.take(src, torch.tensor([0, 2, 5]))

tensor([4, 5, 8])

## repeat the element of tensors


In [ ]:
x = torch.tensor([1, 2, 3])
x.tile((2,))
y = torch.tensor([[1, 2], [3, 4]])
torch.tile(y, (2, 2))

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])

## return the x, y based on conditions

In [ ]:
x = torch.randn(3, 2)
y = torch.ones(3, 2)
x
torch.where(x > 0, x, y)
x = torch.randn(2, 2, dtype=torch.double)
x
torch.where(x > 0, x, 0.)

tensor([[0.0000, 0.0000],
        [0.9232, 0.0000]], dtype=torch.float64)

## compute fractional part of the tensors

In [ ]:
torch.frac(torch.tensor([1, 2.5, -3.2]))

tensor([ 0.0000,  0.5000, -0.2000])

## fill the inf and nan with numbers

In [ ]:
x = torch.tensor([float('nan'), float('inf'), -float('inf'), 3.14])
torch.nan_to_num(x)
torch.nan_to_num(x, nan=2.0)
torch.nan_to_num(x, nan=2.0, posinf=1.0)

tensor([ 2.0000e+00,  1.0000e+00, -3.4028e+38,  3.1400e+00])

## return the sign of the tesnors

In [ ]:
a = torch.tensor([0.7, -1.2, 0., 2.3])
a
torch.sign(a)

tensor([ 1., -1.,  0.,  1.])

## integer part of tensors

In [ ]:
a = torch.randn(4)
a
torch.trunc(a)

tensor([-0., -0., -0., -1.])

## return the product of the tensors

In [ ]:
a = torch.randn(1, 3)
a
torch.prod(a)

tensor(-0.0147)

## count non zero

In [ ]:
x = torch.zeros(3,3)
x[torch.randn(3,3) > 0.5] = 1
x
torch.count_nonzero(x)
torch.count_nonzero(x, dim=0)

tensor([1, 1, 1])

## equal element wise

In [ ]:
torch.eq(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[ True, False],
        [False,  True]])

## unflatten any dimension

In [ ]:
a = torch.randn(5, 12, 3)
torch.unflatten(a, 1, (2, 2, 3, 1, 1)).shape


torch.Size([5, 2, 2, 3, 1, 1, 3])

## Find contiguous in memory

In [ ]:
## Make the elements in memory is a raw
## https://stackoverflow.com/questions/48915810/what-does-contiguous-do-in-pytorch
a = torch.randint(1,10,(3,3))
a.contiguous()
a.is_contiguous()

a.T.is_contiguous()

# How to move to achieve the next element in each dim
a.stride()

(3, 1)

## Expand to new size. Do not allocate memory!

In [4]:
x = torch.tensor([[1], [2], [3]])
x.size()
x.expand(3, 4)

tensor([[1, 1, 1, 1],
        [2, 2, 2, 2],
        [3, 3, 3, 3]])

In [17]:
import torch
from torch.autograd import profiler

l1 = torch.nn.Linear(3,2,bias=True)
a = torch.randn((3,3))
# Enable the profiler
with profiler.profile(use_cuda=False) as prof:
    l1(a)


# Print the profiling results
print(prof)


----------------------  ------------  ------------  ------------  ------------  ------------  ------------  
                  Name    Self CPU %      Self CPU   CPU total %     CPU total  CPU time avg    # of Calls  
----------------------  ------------  ------------  ------------  ------------  ------------  ------------  
          aten::linear         8.92%      14.000us       100.00%     157.000us     157.000us             1  
               aten::t        18.47%      29.000us        29.94%      47.000us      47.000us             1  
       aten::transpose         7.01%      11.000us        11.46%      18.000us      18.000us             1  
      aten::as_strided         4.46%       7.000us         4.46%       7.000us       7.000us             1  
           aten::addmm        47.13%      74.000us        61.15%      96.000us      96.000us             1  
          aten::expand         2.55%       4.000us         3.18%       5.000us       5.000us             1  
      aten::as_stri

## mat1 @ mat2 + M

In [8]:
M = torch.randn(2, 3)
mat1 = torch.randn(2, 3)
mat2 = torch.randn(3, 3)
torch.addmm(M, mat1, mat2)

tensor([[-0.9562, -1.4567, -0.7769],
        [ 0.2622,  1.0937,  3.3500]])

## To check the bottleneck of the code

In [18]:
python -m torch.utils.bottleneck /path/to/source/script.py [args]

SyntaxError: ignored

## how to save and load pytorch model

In [ ]:
# Save checkpoint
checkpoint = {
    'epoch': epoch,
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
    'loss': loss,
    # Add any other information you want to save
}
torch.save(checkpoint, 'checkpoint.pth')

# Load checkpoint
checkpoint = torch.load('checkpoint.pth')
model.load_state_dict(checkpoint['model_state_dict'])
optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
epoch = checkpoint['epoch']
loss = checkpoint['loss']
# Continue training or perform inference


## How to use quantization model
Quantization refers to techniques for performing computations and storing tensors at lower bitwidths than floating point precision. A quantized model executes some or all of the operations on tensors with reduced precision rather than full precision (floating point) values. This allows for a more compact model representation and the use of high performance vectorized operations on many hardware platforms. PyTorch supports INT8 quantization compared to typical FP32 models allowing for a 4x reduction in the model size and a 4x reduction in memory bandwidth requirements. Hardware support for INT8 computations is typically 2 to 4 times faster compared to FP32 compute. Quantization is primarily a technique to speed up inference and only the forward pass is supported for quantized operators.



In [20]:
import torch
import torch.quantization

# Define a simple model
class MyModel(torch.nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.fc = torch.nn.Linear(10, 5)

    def forward(self, x):
        return self.fc(x)

# Create an instance of the model
model = MyModel()

# Create a random input tensor
input_tensor = torch.randn(1, 10)

# Perform the forward pass
output = model(input_tensor)

# Apply post-training static quantization
quantized_model = torch.quantization.quantize_dynamic(
    model, {torch.nn.Linear}, dtype=torch.qint8
)

# Create a random input tensor for the quantized model
quantized_input_tensor = input_tensor#torch.randn(1, 10)

# Perform the forward pass on the quantized model
quantized_output = quantized_model(quantized_input_tensor)

# Print the original and quantized outputs
print("Original output:", output)
print("Quantized output:", quantized_output)


Original output: tensor([[ 0.6606, -0.2118, -0.1486, -0.9009, -0.2390]],
       grad_fn=<AddmmBackward0>)
Quantized output: tensor([[ 0.6513, -0.2097, -0.1451, -0.9051, -0.2283]])
