In [21]:
import torch
import numpy as np

In [22]:
a = torch.arange(22)
a.nelement()

22

In [7]:
torch.flatten(torch.rand((3,3,3)) , start_dim=1)

tensor([[0.1783, 0.8209, 0.0261, 0.3833, 0.7992, 0.1784, 0.8311, 0.6818, 0.6363],
        [0.1738, 0.1535, 0.6898, 0.9236, 0.3581, 0.2190, 0.3062, 0.9067, 0.4804],
        [0.4577, 0.4426, 0.5322, 0.4159, 0.2990, 0.6162, 0.7050, 0.1627, 0.4601]])

In [5]:
a = torch.arange(22)
a.chunk(3)

(tensor([0, 1, 2, 3, 4, 5, 6, 7]),
 tensor([ 8,  9, 10, 11, 12, 13, 14, 15]),
 tensor([16, 17, 18, 19, 20, 21]))

In [24]:
print(a.view(11,2))
torch.permute( a.view(11,2), dims=(1,0))

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21]])


tensor([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20],
        [ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21]])

In [28]:
z = torch.Generator().manual_seed(12)
torch.randperm(4, generator= z)

tensor([3, 2, 1, 0])

if the type of the tensor is any kinds of float.

In [33]:
a.is_floating_point()

False

Number of elements is tensor

In [35]:
a.numel()

22

Convert object to tesor

In [41]:
torch.asarray((1,2,3,4.0))

# keep grads
torch.as_tensor([1,2,3])

tensor([1, 2, 3])

Convert from np

In [44]:
torch.from_numpy(np.arange(10))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

indeces of each non-zero element

In [27]:
print(a.view(-1,2))
a.view(-1,2).argwhere()

tensor([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21]])


tensor([[ 0,  1],
        [ 1,  0],
        [ 1,  1],
        [ 2,  0],
        [ 2,  1],
        [ 3,  0],
        [ 3,  1],
        [ 4,  0],
        [ 4,  1],
        [ 5,  0],
        [ 5,  1],
        [ 6,  0],
        [ 6,  1],
        [ 7,  0],
        [ 7,  1],
        [ 8,  0],
        [ 8,  1],
        [ 9,  0],
        [ 9,  1],
        [10,  0],
        [10,  1]])

Horizontally split the tensor

In [28]:
t = torch.arange(16.0).reshape(4,4)
t
torch.hsplit(t, 2)
#torch.hsplit(t, [3, 6])

(tensor([[ 0.,  1.],
         [ 4.,  5.],
         [ 8.,  9.],
         [12., 13.]]),
 tensor([[ 2.,  3.],
         [ 6.,  7.],
         [10., 11.],
         [14., 15.]]))

Split the tesnor in depth

In [67]:
t = torch.arange(16.0).reshape(2, 2, 4)
t
torch.dsplit(t, 2)

(tensor([[[ 0.,  1.],
          [ 4.,  5.]],
 
         [[ 8.,  9.],
          [12., 13.]]]),
 tensor([[[ 2.,  3.],
          [ 6.,  7.]],
 
         [[10., 11.],
          [14., 15.]]]))

Select the index by dim

In [30]:
x = torch.randn(3, 4)
x
indices = torch.tensor([0, 2])
#torch.index_select(x, 0, indices)
torch.index_select(x, 1, indices)

tensor([[-0.4170, -0.8916],
        [ 0.2220,  0.2988],
        [-1.3007, -0.8090]])

select by mask

In [70]:
x = torch.randn(3, 4)
x
mask = x.ge(0.5)
mask
torch.masked_select(x, mask)

tensor([0.5809, 0.5545, 1.6812, 0.6939, 1.2305])

split the tensor

In [33]:
a = torch.arange(10).reshape(5,2)
a
torch.split(a, 1)
torch.split(a, [1,4])

(tensor([[0, 1]]),
 tensor([[2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]))

return the elemnts by the index view as 1-D

In [34]:
src = torch.tensor([[4, 3, 5],
                    [6, 7, 8]])
torch.take(src, torch.tensor([0, 2, 5]))

tensor([4, 5, 8])

repeat the elementof tensors


In [73]:
x = torch.tensor([1, 2, 3])
x.tile((2,))
y = torch.tensor([[1, 2], [3, 4]])
torch.tile(y, (2, 2))

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])

return the x, y based on conditions

In [74]:
x = torch.randn(3, 2)
y = torch.ones(3, 2)
x
torch.where(x > 0, x, y)
x = torch.randn(2, 2, dtype=torch.double)
x
torch.where(x > 0, x, 0.)

tensor([[0.0000, 0.0000],
        [0.9232, 0.0000]], dtype=torch.float64)

compute fractional part of the tensors

In [2]:
torch.frac(torch.tensor([1, 2.5, -3.2]))

tensor([ 0.0000,  0.5000, -0.2000])

fill the inf and nan with numbers

In [4]:
x = torch.tensor([float('nan'), float('inf'), -float('inf'), 3.14])
torch.nan_to_num(x)
torch.nan_to_num(x, nan=2.0)
torch.nan_to_num(x, nan=2.0, posinf=1.0)

tensor([ 2.0000e+00,  1.0000e+00, -3.4028e+38,  3.1400e+00])

return the sign of the tesnors

In [6]:
a = torch.tensor([0.7, -1.2, 0., 2.3])
a
torch.sign(a)

tensor([ 1., -1.,  0.,  1.])

integer part of tensors

In [7]:
a = torch.randn(4)
a
torch.trunc(a)

tensor([-0., -0., -0., -1.])

return the product of the tensors

In [8]:
a = torch.randn(1, 3)
a
torch.prod(a)

tensor(-0.0147)

count non zero

In [10]:
x = torch.zeros(3,3)
x[torch.randn(3,3) > 0.5] = 1
x
torch.count_nonzero(x)
torch.count_nonzero(x, dim=0)

tensor([1, 1, 1])

equal element wise

In [11]:
torch.eq(torch.tensor([[1, 2], [3, 4]]), torch.tensor([[1, 1], [4, 4]]))

tensor([[ True, False],
        [False,  True]])

unflatten any dimension

In [20]:
a = torch.randn(5, 12, 3)
torch.unflatten(a, 1, (2, 2, 3, 1, 1)).shape


torch.Size([5, 2, 2, 3, 1, 1, 3])