<a href="https://colab.research.google.com/github/M-Amrollahi/Personal-Notes/blob/master/how_conv1-2_works.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [93]:
import torch
import numpy as np
import torch.nn as nn

In [94]:
a1 = torch.arange(0,20).reshape((1,2,2,5))
a1

tensor([[[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9]],

         [[10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19]]]])

In [95]:
conv1 = nn.Conv2d(in_channels=2, out_channels=2, kernel_size=(2,2), bias=False)
print(conv1.weight)
b1 = conv1(a1.float())
b1


Parameter containing:
tensor([[[[ 0.0700, -0.0102],
          [ 0.2216, -0.2729]],

         [[-0.2514,  0.2298],
          [ 0.3157,  0.2807]]],


        [[[-0.2399, -0.2296],
          [-0.2525, -0.1479]],

         [[-0.3171,  0.0649],
          [-0.1246, -0.0914]]]], requires_grad=True)


tensor([[[[  8.6995,   9.2827,   9.8659,  10.4491]],

         [[ -8.1674,  -9.5054, -10.8434, -12.1814]]]],
       grad_fn=<ConvolutionBackward0>)

In [96]:
a3 = torch.arange(0,24).reshape((2,2,6))
a3

tensor([[[ 0,  1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10, 11]],

        [[12, 13, 14, 15, 16, 17],
         [18, 19, 20, 21, 22, 23]]])

In [97]:
conv2 = nn.Conv1d(2,2,2,bias=False)
conv2.weight.shape

torch.Size([2, 2, 2])

In [98]:
conv2(a3.float())

tensor([[[ -4.9195,  -6.3971,  -7.8748,  -9.3524, -10.8301],
         [  2.3737,   2.6818,   2.9899,   3.2980,   3.6061]],

        [[-22.6512, -24.1288, -25.6065, -27.0841, -28.5618],
         [  6.0710,   6.3791,   6.6872,   6.9953,   7.3034]]],
       grad_fn=<ConvolutionBackward0>)

In [100]:
(conv2.weight[0]*a3[0,:,1:3]).sum()

tensor(-6.3971, grad_fn=<SumBackward0>)